import fgarcade as ge

@ge.create_platformer('Trabalho DS')
def game(world):
    
    #------------------- PARTE VALADAO --------------------
    
    world.player_initial_position = (2, 5)
    
    world.create_tower(12, coords=(0, 1))
    world.create_ground(3, coords=(6, 1))
    world.create_platform(1, coords=(2, 8))
    world.create_platform(3, coords=(4, 5))
    world.create_platform(3, coords=(10, 4))
    world.create_ground(23, coords=(0, 0), smooth_ends=False)
    world.create_ramp('up', 6, coords=(15, 1))
    world.create_ground(2, coords=(21, 6), smooth_ends=False, height=6)
    world.create_platform(3, coords=(28, 5))
    world.create_platform(3, coords=(35, 6))
    world.create_platform(3, coords=(42, 3))
    world.create_ground(9, coords=(49, 0))
    world.create_tower(20, coords=(51, 3))
    world.create_tower(13, coords=(56, 1))
    world.create_platform(1, coords=(55, 2))
    world.create_platform(1, coords=(52, 5))
    world.create_platform(1, coords=(55, 8))
    world.create_platform(1, coords=(52, 11))
    world.create_ground(2, coords=(60, 11))
    world.create_ground(3, coords=(65, 9))
    world.create_ground(3, coords=(70, 7))
    world.create_ground(2, coords=(75, 4))
    world.create_ground(2, coords=(80, 0))
    world.create_ramp('up', 4, coords=(82, 0))
    world.create_ramp('up', 4, coords=(88, 4))
    world.create_tower(5, coords=(88, 0))
    world.create_tower(6, coords=(89, 0))
    world.create_tower(7, coords=(90, 0))
    world.create_tower(7, coords=(91, 1))
    world.create_ground(3, coords=(91, -1))
    world.create_platform(1, coords=(94, 2))
    world.create_platform(1, coords=(97, 4))
    world.create_ground(3, coords=(102, 5))
    world.create_platform(3, coords=(96, 7))
    world.create_ground(3, coords=(107, 0))
    world.create_ramp('up', 6, coords=(114, 0))

    #--------------------- PARTE AVELINO -----------------------------
    world.create_tower(7, coords=(120,0))
    world.create_tower(8, coords=(121,0))
    world.create_tower(9, coords=(122,0))
    world.create_tower(10, coords=(124,0))   
    world.create_tower(11, coords=(126,0))
    world.create_tower(12, coords=(128,0))
    world.create_tower(13, coords=(129,0))
    world.create_tower(14, coords=(131,0))
    world.create_ground(3, coords=(132, 13))
    world.create_platform(1, coords=(132,6))
    world.create_platform(1, coords=(132,2))
    world.create_ground(2, coords=(132, 0))
    world.create_ground(2, coords=(138, 0))
    world.create_tower(20, coords=(144,2))
    world.create_ground(2, coords=(143.5, 0))
    world.create_tower(3, coords=(149,0))
    world.create_platform(1, coords=(153,4))
    world.create_ground(6, coords=(145,6))
    world.create_tower(10, coords=(155,0))
    world.create_ground(6, coords=(145,6))
    world.create_ground(6, coords=(149,9),end='sharp')
    world.create_platform(2, coords=(158,4))
    world.create_ground(2, coords=(161,0), smooth_ends=False)
    world.create_ramp('up', 10, coords=(163,0))
    world.create_ground(20, coords=(178,0))
    world.create_ground(3, coords=(182,1))
    world.create_tower(5, coords=(188,2))
    world.create_tower(5, coords=(193,2))
    world.create_ground(4, coords=(189,7))
    world.create_ground(2, coords=(190,8))
    world.create_ground(1, coords=(190.5,9))
    world.create_platform(1, coords=(187,4))
    world.create_tower(20, coords=(197,0))


if __name__ == "__main__":
    game.run()